# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MRI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1121, 855)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 199, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 82, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 115, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(173, 115, 86, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 199, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(110, 82, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 115, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(173, 115, 86, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 199, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 115, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 115, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(173, 115, 86, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        MainWindow.setPalette(palette)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Wdg_Original = QtWidgets.QWidget(self.centralwidget)
        self.Wdg_Original.setGeometry(QtCore.QRect(30, 30, 411, 361))
        self.Wdg_Original.setAcceptDrops(False)
        self.Wdg_Original.setAutoFillBackground(True)
        self.Wdg_Original.setObjectName("Wdg_Original")
        self.Wdg_Processed = QtWidgets.QWidget(self.centralwidget)
        self.Wdg_Processed.setGeometry(QtCore.QRect(29, 419, 411, 361))
        self.Wdg_Processed.setAutoFillBackground(True)
        self.Wdg_Processed.setObjectName("Wdg_Processed")
        self.Wdg_Label = QtWidgets.QWidget(self.centralwidget)
        self.Wdg_Label.setGeometry(QtCore.QRect(470, 420, 411, 361))
        self.Wdg_Label.setAutoFillBackground(True)
        self.Wdg_Label.setObjectName("Wdg_Label")
        self.Slice_Slider = QtWidgets.QSlider(self.centralwidget)
        self.Slice_Slider.setGeometry(QtCore.QRect(470, 380, 411, 22))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 73))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(181, 77, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(199, 25, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 73))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(181, 77, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(199, 25, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(181, 77, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(181, 77, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.Slice_Slider.setPalette(palette)
        self.Slice_Slider.setStyleSheet("QSlider::handle:horizontal {background-color: black;}")
        self.Slice_Slider.setMaximum(30)
        self.Slice_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.Slice_Slider.setObjectName("Slice_Slider")
        self.Push_Buttons_Group_Box = QtWidgets.QGroupBox(self.centralwidget)
        self.Push_Buttons_Group_Box.setGeometry(QtCore.QRect(652, 30, 181, 201))
        self.Push_Buttons_Group_Box.setObjectName("Push_Buttons_Group_Box")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Push_Buttons_Group_Box)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.PB_Load_Image = QtWidgets.QPushButton(self.Push_Buttons_Group_Box)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.PB_Load_Image.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PB_Load_Image.setFont(font)
        self.PB_Load_Image.setObjectName("PB_Load_Image")
        self.verticalLayout_2.addWidget(self.PB_Load_Image)
        self.PB_Process_Image = QtWidgets.QPushButton(self.Push_Buttons_Group_Box)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.PB_Process_Image.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PB_Process_Image.setFont(font)
        self.PB_Process_Image.setObjectName("PB_Process_Image")
        self.verticalLayout_2.addWidget(self.PB_Process_Image)
        self.PB_Save_Results = QtWidgets.QPushButton(self.Push_Buttons_Group_Box)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.PB_Save_Results.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PB_Save_Results.setFont(font)
        self.PB_Save_Results.setObjectName("PB_Save_Results")
        self.verticalLayout_2.addWidget(self.PB_Save_Results)
        self.Labels_Group_Box = QtWidgets.QGroupBox(self.centralwidget)
        self.Labels_Group_Box.setGeometry(QtCore.QRect(460, 30, 186, 223))
        self.Labels_Group_Box.setObjectName("Labels_Group_Box")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Labels_Group_Box)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Lb_Metric_1_name = QtWidgets.QLabel(self.Labels_Group_Box)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Lb_Metric_1_name.setFont(font)
        self.Lb_Metric_1_name.setObjectName("Lb_Metric_1_name")
        self.verticalLayout.addWidget(self.Lb_Metric_1_name)
        self.line = QtWidgets.QFrame(self.Labels_Group_Box)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.Lb_Metric_1_value = QtWidgets.QLabel(self.Labels_Group_Box)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Lb_Metric_1_value.setFont(font)
        self.Lb_Metric_1_value.setObjectName("Lb_Metric_1_value")
        self.verticalLayout.addWidget(self.Lb_Metric_1_value)
        self.line_2 = QtWidgets.QFrame(self.Labels_Group_Box)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_2.setFont(font)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.Lb_Patient_Class = QtWidgets.QLabel(self.Labels_Group_Box)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Lb_Patient_Class.setFont(font)
        self.Lb_Patient_Class.setObjectName("Lb_Patient_Class")
        self.verticalLayout.addWidget(self.Lb_Patient_Class)
        self.line_3 = QtWidgets.QFrame(self.Labels_Group_Box)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.Lb_Patient_Value = QtWidgets.QLabel(self.Labels_Group_Box)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Lb_Patient_Value.setFont(font)
        self.Lb_Patient_Value.setObjectName("Lb_Patient_Value")
        self.verticalLayout.addWidget(self.Lb_Patient_Value)
        self.LCD_Slice_Number = QtWidgets.QLCDNumber(self.centralwidget)
        self.LCD_Slice_Number.setGeometry(QtCore.QRect(890, 380, 51, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 214, 157))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(164, 246, 246))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 214, 157))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(164, 246, 246))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 214, 157))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(34, 115, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(164, 246, 246))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        self.LCD_Slice_Number.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.LCD_Slice_Number.setFont(font)
        self.LCD_Slice_Number.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.LCD_Slice_Number.setAutoFillBackground(True)
        self.LCD_Slice_Number.setDigitCount(3)
        self.LCD_Slice_Number.setObjectName("LCD_Slice_Number")
        self.Debug_Text_Browser = QtWidgets.QTextBrowser(self.centralwidget)
        self.Debug_Text_Browser.setGeometry(QtCore.QRect(450, 270, 511, 81))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(163, 179, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(163, 179, 93))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.Debug_Text_Browser.setPalette(palette)
        self.Debug_Text_Browser.setObjectName("Debug_Text_Browser")
        self.Lb_ImagePath = QtWidgets.QLabel(self.centralwidget)
        self.Lb_ImagePath.setGeometry(QtCore.QRect(660, 240, 441, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Lb_ImagePath.setFont(font)
        self.Lb_ImagePath.setObjectName("Lb_ImagePath")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(850, 120, 231, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.progressBar.setPalette(palette)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.Lb_Belal = QtWidgets.QLabel(self.centralwidget)
        self.Lb_Belal.setGeometry(QtCore.QRect(840, 10, 271, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(216, 216, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(216, 216, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.Lb_Belal.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.Lb_Belal.setFont(font)
        self.Lb_Belal.setObjectName("Lb_Belal")
        self.Lb_Original_Image_Title = QtWidgets.QLabel(self.centralwidget)
        self.Lb_Original_Image_Title.setGeometry(QtCore.QRect(140, 10, 111, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(60, 255, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 255, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.Lb_Original_Image_Title.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Lb_Original_Image_Title.setFont(font)
        self.Lb_Original_Image_Title.setObjectName("Lb_Original_Image_Title")
        self.Lb_Processed_Image_Title = QtWidgets.QLabel(self.centralwidget)
        self.Lb_Processed_Image_Title.setGeometry(QtCore.QRect(130, 390, 141, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(60, 255, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 255, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.Lb_Processed_Image_Title.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Lb_Processed_Image_Title.setFont(font)
        self.Lb_Processed_Image_Title.setObjectName("Lb_Processed_Image_Title")
        self.Lb_Ground_Truth_Title = QtWidgets.QLabel(self.centralwidget)
        self.Lb_Ground_Truth_Title.setGeometry(QtCore.QRect(600, 400, 121, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(60, 255, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 255, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.Lb_Ground_Truth_Title.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Lb_Ground_Truth_Title.setFont(font)
        self.Lb_Ground_Truth_Title.setObjectName("Lb_Ground_Truth_Title")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(490, 360, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1121, 26))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionFile = QtWidgets.QAction(MainWindow)
        self.actionFile.setObjectName("actionFile")
        self.actionLoad_Dicom = QtWidgets.QAction(MainWindow)
        self.actionLoad_Dicom.setObjectName("actionLoad_Dicom")
        self.actionSave_Session = QtWidgets.QAction(MainWindow)
        self.actionSave_Session.setObjectName("actionSave_Session")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionParameters = QtWidgets.QAction(MainWindow)
        self.actionParameters.setObjectName("actionParameters")
        self.actionDocumentation = QtWidgets.QAction(MainWindow)
        self.actionDocumentation.setObjectName("actionDocumentation")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionContact_Us = QtWidgets.QAction(MainWindow)
        self.actionContact_Us.setObjectName("actionContact_Us")
        self.actionChange_View = QtWidgets.QAction(MainWindow)
        self.actionChange_View.setObjectName("actionChange_View")
        self.menuMenu.addAction(self.actionFile)
        self.menuMenu.addAction(self.actionLoad_Dicom)
        self.menuMenu.addAction(self.actionSave_Session)
        self.menuMenu.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionParameters)
        self.menuView.addAction(self.actionChange_View)
        self.menuHelp.addAction(self.actionDocumentation)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionContact_Us)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.Slice_Slider.valueChanged['int'].connect(self.LCD_Slice_Number.display)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Wdg_Original.setStatusTip(_translate("MainWindow", "Original Image"))
        self.Wdg_Processed.setStatusTip(_translate("MainWindow", "Processed Image"))
        self.Wdg_Label.setStatusTip(_translate("MainWindow", "Label Ground-Truth"))
        self.Slice_Slider.setStatusTip(_translate("MainWindow", "Slide to change slide number"))
        self.Push_Buttons_Group_Box.setTitle(_translate("MainWindow", "Push_Buttons"))
        self.PB_Load_Image.setStatusTip(_translate("MainWindow", "click to load an image, or press Ctrl+O for Nifti, Ctrl+D for Dicom"))
        self.PB_Load_Image.setText(_translate("MainWindow", "Load Image"))
        self.PB_Load_Image.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.PB_Process_Image.setStatusTip(_translate("MainWindow", "Press to start working, or click Ctrl+P"))
        self.PB_Process_Image.setText(_translate("MainWindow", "Process Image"))
        self.PB_Process_Image.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.PB_Save_Results.setStatusTip(_translate("MainWindow", "press here to save the whole session, or just click Ctrl+S"))
        self.PB_Save_Results.setText(_translate("MainWindow", "save results"))
        self.PB_Save_Results.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.Labels_Group_Box.setTitle(_translate("MainWindow", "Labels"))
        self.Lb_Metric_1_name.setStatusTip(_translate("MainWindow", "Metric_1_title"))
        self.Lb_Metric_1_name.setText(_translate("MainWindow", "metric_name"))
        self.Lb_Metric_1_value.setStatusTip(_translate("MainWindow", "Value of Metric_1"))
        self.Lb_Metric_1_value.setText(_translate("MainWindow", "metric_value"))
        self.Lb_Patient_Class.setStatusTip(_translate("MainWindow", "Class of the patient(Normal-Sick-Corona)"))
        self.Lb_Patient_Class.setText(_translate("MainWindow", "Patient Class"))
        self.Lb_Patient_Value.setStatusTip(_translate("MainWindow", "See class of the patient here"))
        self.Lb_Patient_Value.setText(_translate("MainWindow", "Patient_Value"))
        self.LCD_Slice_Number.setStatusTip(_translate("MainWindow", "Slide_Number"))
        self.LCD_Slice_Number.setAccessibleDescription(_translate("MainWindow", "0"))
        self.Lb_ImagePath.setStatusTip(_translate("MainWindow", "Image Path"))
        self.Lb_ImagePath.setText(_translate("MainWindow", "Image Path"))
        self.Lb_Belal.setText(_translate("MainWindow", "GUI Designed By Belal Hmedan\n"
"Email: Belal_Hmedan@etu.u-bourgogne.fr"))
        self.Lb_Original_Image_Title.setText(_translate("MainWindow", "Original Image"))
        self.Lb_Processed_Image_Title.setText(_translate("MainWindow", "Processed Image"))
        self.Lb_Ground_Truth_Title.setText(_translate("MainWindow", "Ground_Truth"))
        self.label.setText(_translate("MainWindow", "Slice Number"))
        self.menuMenu.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionFile.setText(_translate("MainWindow", "Load Nifti"))
        self.actionFile.setStatusTip(_translate("MainWindow", "Press Here to load your Nifti Image, or Simply click Ctrl+O"))
        self.actionFile.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionLoad_Dicom.setText(_translate("MainWindow", "Load Dicom"))
        self.actionLoad_Dicom.setStatusTip(_translate("MainWindow", "Press Here to load your Dicom Image, or simply click Ctrl+D"))
        self.actionLoad_Dicom.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionSave_Session.setText(_translate("MainWindow", "Save Session"))
        self.actionSave_Session.setStatusTip(_translate("MainWindow", "Click here to save the session, or just click Ctrl+S"))
        self.actionSave_Session.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setStatusTip(_translate("MainWindow", "Exit the Session, you can just click Ctrl+Q"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionParameters.setText(_translate("MainWindow", "Parameters"))
        self.actionParameters.setStatusTip(_translate("MainWindow", "Press Here to Adjust your Parameters"))
        self.actionDocumentation.setText(_translate("MainWindow", "Documentation"))
        self.actionDocumentation.setStatusTip(_translate("MainWindow", "Press here to read the documentation"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionAbout.setStatusTip(_translate("MainWindow", "About This App"))
        self.actionContact_Us.setText(_translate("MainWindow", "Contact Us"))
        self.actionContact_Us.setStatusTip(_translate("MainWindow", "Press here to contact us"))
        self.actionChange_View.setText(_translate("MainWindow", "Change View"))
        self.actionChange_View.setStatusTip(_translate("MainWindow", "Press Here to change View"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
